'''import numpy as np
a=np.array([5,6,7,8,9,1])
print(a)
sum=np.sum(a)
print(sum)
avg=np.mean(a)
print(avg)
mi=np.min(a)
print(mi)
ma=np.max(a)
print(ma)
ma_i=np.argmax(a)
print(ma_i)
mi_i=np.argmin(a)
print(mi_i)
st=np.std(a)
print(st)
var=np.var(a)
print(var)'''

import pandas as pd
df=pd.DataFrame([[4,5,6],[7,8,9],[1,2,3]],columns=['math','python','java'])
print(df)
print(df.sum())
print(df.agg(['sum','min','max','count','size','std']))
print(df.describe())
print(df.groupby("java"))
